### PR TITLE
test: fix build for E2E test

### PR DESCRIPTION
**Pull request by kakcy**
A build error occurred related to [E2ETest](https://github.com/bucketeer-io/ios-client-sdk/actions/runs/6887151181/job/18733901932#step:3:1210).

example:
/ios-client-sdk/BucketeerTests/E2E/E2EEventTests.swift:62:51

```
error: value of type 'any DataModule' has no member 'eventDao'
            let events = try component.dataModule.eventDao.getEvents()
```

This seems to be caused by https://github.com/bucketeer-io/ios-client-sdk/pull/51 not considering the response to https://github.com/bucketeer-io/ios-client-sdk/pull/49.

# Changes

- [x] unify `EventDao` to `EventSQLDao`
- [x] fix build error for `testDefaultEvaluationEvents()`

### CODE REVIEW

**Review by kakcy — COMMENTED** [review]
Hi @cre8ivejp, 
In accordance with the policy of #49, the file name and code have been corrected so that "EventDao" is unified with "EventSQLDao" even in places other than build errors.

Please check this PR while you are free.

**Comment by duyhungtnn** [comment]
Thank @kakcy , I did #51  while #49  was in review. So I could not use any changes from #49. 

The CI had failed, but I missed that https://github.com/bucketeer-io/ios-client-sdk/actions/runs/6887151181

**Review by duyhungtnn — APPROVED** [review]
I tested on my local machine. It works. 👍🏻

**Review by cre8ivejp — APPROVED** [review]
Looks good!
Thank you!

**Comment by kakcy** [comment]
Thank you for your review 🙇

**Pull request merged**
