### PR TITLE
build: introduce XcodeGen

### PR DESCRIPTION
**Pull request by kakcy**
Introduce [XcodeGen](https://github.com/yonaskolb/XcodeGen) to change the way .xcodeproj is managed.

# Changes

- [x] Introduce XcodeGen using mint
- [x] Exclude `.xcodeproj` from the commit target
- [x] Upload `Bucketeer.xcframework.zip` at creating the release tag
_The Carthage build task requires an Xcode project file, which will no longer exist after this PR.
Therefore, [Carthage uses zip file](https://github.com/Carthage/Carthage?tab=readme-ov-file#archive-prebuilt-frameworks-into-zip-files
) uploaded to release._

### CODE REVIEW

**Comment by kakcy** [comment]
Hi @duyhungtnn,
I introduced _XcodeGen_ because `.xcodeproj` is prone to conflicts and challenging to review.
I created it based on the project.yml generated by [XcodeGen's migration function](https://github.com/yonaskolb/XcodeGen/pull/735).

Please check this PR while you are free.

**Comment by duyhungtnn** [comment]
Hi @kakcy  
I was thinking about the project.yml missing the background mode settings.
But when I generated the project. It still has that setting. So that the generated project file seems good.

Could you please help me understand how to set it on this PR ?

Screenshot 2023-12-15 at 09 26 03

**Comment by kakcy** [comment]
Hi @duyhungtnn , thank you for review.

My understanding that background mode settings are managed in each app's plist.

> Xcode adds the UIBackgroundModes array to your app’s Info.plist file, if it isn’t already present, and uses the modes you select to populate the array with the necessary values.
Bucketeer_—_Bucketeer_xcodeproj

Therefore, I don't think the introduction of XcodeGen will affect the background mode settings, what do you think?

I apologize if I misunderstood your question, but I would like to know more about your question.

（This additional [commit](https://github.com/bucketeer-io/ios-client-sdk/pull/58/commits/48c7de5a4baccbdeacf24e4b48a6d1fe9c244dba) has nothing to do with your question.）

**Review by duyhungtnn — APPROVED** [review]
thank @kakcy 
I understood. The background configuration come from the plist file for each current target. Its not from the project.yml

This PR LGTM

**Comment by kakcy** [comment]
Thank you for your review 🙇

**Review by cre8ivejp — APPROVED** [review]
Thank you!

**Comment by kakcy** [comment]
Thank you for confirming！

**Pull request merged**
