### PR TITLE
chore: reduce unnecessary API

### PR DESCRIPTION
**Pull request by duyhungtnn**
Refs: https://github.com/bucketeer-io/android-client-sdk/pull/89
###  Changes
- [x] rename `EventDao` to `EventSQLDao`
- [x] do not allow changes `evaluation_id` directly. It should be done together when using the method "deleteAllAndInsert & update" of the `EvaluationStorage`
- [x] fixed https://github.com/bucketeer-io/ios-client-sdk/issues/25 
- [x] fixed https://github.com/bucketeer-io/ios-client-sdk/issues/34

### CODE REVIEW

**Comment by duyhungtnn** [comment]
will close https://github.com/bucketeer-io/ios-client-sdk/issues/34

**Comment by duyhungtnn** [comment]
will close https://github.com/bucketeer-io/ios-client-sdk/issues/25

**Comment by duyhungtnn** [comment]
hi, @cre8ivejp please help me to take a look at this PR. Thank you.

**Review by cre8ivejp — APPROVED** [review]
Thank you!

**Pull request merged**
